const RightSidebar = () => {
  return (
    <div className="flex flex-col justify-between bg-[#16110B] h-screen max-w-[250px] w-max">
      {/*Header*/}
      <div className=" border-b-2 border-b-[#675D49] px-5">
        <div className=" py-2">
            <h1 className="text-[#675D49]">Surfer AI</h1>
        </div>
      </div>
      {/*Actual input area*/}
      <div className="w-full flex flex-col justify-center items-center">
        <input type="text" className="" />
        <span>AI can be inaccurate. Check the code generated by the model if unsure.</span>
      </div>
    </div>
  )
}

export default RightSidebar
